### ISSUE TITLE
only import polygon centroids as POIs

### ISSUE THREAD

**Issue by sevko** [pelias/quattroshapes#15]
With the introduction of the new [admin-lookup](https://github.com/pelias/admin-lookup), which builds administrative hierarchies without querying elasticsearch Quattro types (as the old `hierarchy-lookup` did), we don't need to import polygons themselves, and should import their centroids as POIs instead. This'll involve ripping out significant chunks of the code and will result in a slimmer and *much* faster importer.

**Comment by sevko** [comment]
Will simultaneously migrate the importer to `pelias-model`.

**Comment by sevko** [comment]
If we decide to expose a coarse reverse-geocoding endpoint in the Pelias API we'll need to import polygons, so I'm hesitant about implementing this until that's settled. Putting on hold for now.

**Comment by missinglink** [comment]
this issue was resolved some time ago
