### ISSUE TITLE
geometry errors (null bounds)

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#2]
Prior to fixing https://github.com/pelias/quattroshapes-pipeline/issues/1 there were 1-2 records which returned a `null` bounds and therefore caused the import to fail.

Because of better error handling those records no longer cause a fatal error; however they are still not being imported properly.

This ticket is to investigate how many error, why they error and to get them importing correctly.
As far as I know this only affects the `local_admin` import, which used to fail around the time the index stats hit 2500.

**Comment by sevko** [comment]
I'm working on removing `null`/empty geometries and computing and exporting centroids in the Quattro preprocessing scripts in pelias/quattroshapes-patch, which will mean that we don't need to worry about it in the importer.
