### ISSUE TITLE
Use population and popularity values 

### ISSUE THREAD

**Issue by hkrishna** [pelias/quattroshapes#20]
Lets use population and popularity values for polygons/shapes when available. (Using pelias-model's population and popularity setter and getters)

**Comment by missinglink** [comment]
At least one of the quattroshapes files has geonames concordances.

**Comment by sevko** [comment]
@missinglink, what does that have to do with population/popularity?

**Comment by missinglink** [comment]
Oh sorry that comment was not very clear, I could be wrong but I vaguely remember that the quattroshapes data doesn't contain population information but in some cases we could look up that info from an associated geonames record.
