### ISSUE TITLE
Munich/München not found

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#22]
I can't seem to find the Germany city of Munich using the English name or the German name `München`.

http://pelias.mapzen.com/search?input=M%C3%BCnchen&layers=admin&lat=48.1549107&lon=11.5418358

https://nominatim.openstreetmap.org/details.php?place_id=127333514

opening a related OSM ticket for:
http://pelias.mapzen.com/doc?id=osmnode:1700534808
http://www.openstreetmap.org/node/1700534808

**Comment by missinglink** [comment]
found it, there are character encoding issues:

```javascript
    {
      "type": "Feature",
      "properties": {
        "id": "299875281",
        "layer": "osmway",
        "name": "Hauptbahnhof",
        "alpha3": "DEU",
        "admin0": "Germany",
        "admin1": "Bayern",
        "admin2": "Muenchen",
        "locality": "MÃ¼nchen",
        "neighborhood": "Isarvorstadt",
        "category": [],
        "address": {},
        "text": "Hauptbahnhof, MÃ¼nchen, Bayern"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          11.560277,
          48.140261
        ]
      }
    },
```

**Comment by missinglink** [comment]
related https://github.com/pelias/quattroshapes-patch/issues/9

**Comment by nvkelso** [comment]
Suspect this is an encoding issue in the DBF file. The CPG file seems to be UTF-8, but the DBF doesn't. Suggest a data fix in the source file.

**Comment by orangejulius** [comment]
Amazingly, both can be found now, although there is still an encoding issue in the name.
