### ISSUE TITLE
test coverage / refactor

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#26]
this repo is old and has poor test coverage, it's functionally is sound but it's code is messy and inconsistent with other importers, in general it could do with a face-lift and the structure could be based off pelias/openstreetmap which is much cleaner and well tested.

**Comment by missinglink** [comment]
@dianashk what do you think about setting aside some time to clean up with repo and resolve some of the open issues, or do you think we should hold off until we know more about the related data project?

**Comment by riordan** [comment]
Both would be wise. Might be easiest for you to chat with the Data team
next week when Kelso & Aaron are in NYC.

On 7/20/15 10:51, Peter Johnson a.k.a. insertcoffee wrote:
>
> @dianashk <https://github.com/dianashk> what do you think about
> setting aside some time to clean up with repo and resolve some of the
> open issues, or do you think we should hold off until we know more
> about the related data project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/quattroshapes/issues/26#issuecomment-122909252>.
>

-- 
-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen

**Comment by orangejulius** [comment]
We no longer are maintaining this repo, so we will not be adding tests.
