### ISSUE TITLE
Northern

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#30]
```
{
      "type": "Feature",
      "properties": {
        "id": "822:adm1:fj:fji:northern",
        "gid": "qs:region:822:adm1:fj:fji:northern",
        "layer": "region",
        "source": "qs",
        "name": "Northern",
        "region": "Northern",
        "confidence": 0.654,
        "label": "Northern"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          156.235595135516,
          -16.6122320470824
        ]
      }
    },
```

**Comment by riordan** [comment]
@missinglink, does quattroshapes -> WOF fix this?

**Comment by riordan** [comment]
@missinglink also what does this mean?! Is there treasure located there?!!!!

**Comment by missinglink** [comment]
precious! :ring: it looks like this place is called `Northern`, I can't spear to whether its 1) a data error in QS, 2) it's actually called "Northern" and 3) If WOF will fix it if it's broken.

**Comment by dianashk** [comment]
Close this in favor of new WOF issue (TBD) to rename Northern to Northern Division.
